Change Strengths to readonly and reorganize Expansions
hc-tcg/hc-tcg pull request #760
Opened 2024-07-30 03:24 UTC by Benji42

With these changes, the Strengths dict and the Expansions dict are both read only. This is important so people don't accidentally think they are supposed to modify these.
In addition, the expansions are now set up in a more intuitive way, and there also shouldn't be typing issues with them anymore, like there were in the past.

2024-07-30 05:12 UTC, Lunarmagpie commented on common/const/expansions.ts
> +}
I think its overkill to have properties for the expansion when there is no other properties

2024-07-30 05:14 UTC, Lunarmagpie commented on common/const/strengths.ts
> +}
This is the evil option, but there is nothing I like more than a good old metatype 
```suggestion
type Strengths = {
	readonly [Type in TypeT]: Array<TypeT>
}
```

2024-07-30 05:25 UTC, Rvtar commented
Now I actually have to learn how you set up the system.

2024-07-30 05:29 UTC, Lunarmagpie commented
It would be best if you use this type whenever possible https://www.typescriptlang.org/docs/handbook/utility-types.html#readonlytype

2024-07-30 05:43 UTC, Rvtar commented
I meant how I did my Weakness PR last time was messing with this since it's simpler to learn than how it currently works.

2024-07-31 01:16 UTC, Lunarmagpie requested changes

2024-07-31 01:16 UTC, Lunarmagpie commented on common/const/strengths.ts
> +type strengths = {
This is a type so it must be capital

2024-07-31 01:24 UTC, Benji42 commented on common/const/strengths.ts
> +type strengths = {
Fixed

2024-07-31 01:25 UTC, Lunarmagpie approved these changes

2024-07-31 01:25 UTC, merged