Jopacity fixes
hc-tcg/hc-tcg pull request #887
Opened 2024-09-12 06:02 UTC by Screaper91

- Fixes Jopacity dealing too much damage when opponent's Invisibility flips tails
- Fixes Puppetry/Role Play continuing to deal reduced damage until a primary is used after using Jopacity

2024-09-12 12:46 UTC, Lunarmagpie requested changes
I don't like that the chroma keyed logic has been moved to Beetlejhost. I think that effects should be able to be applied and work on any hermit to keep the code easy to follow.

2024-09-12 15:11 UTC, Screaper91 commented
Chroma Keyed is single purposed for Beetlejhost's Jopacity, it would not make sense for it to be re-used for another decaying special attack because then swapping between the two attacks would not reset the counter. I could move the damage reduction logic back, but it would require adding something like `AttackModel.isOrigin(source: Card): boolean` to check that `BeetlejhostRare` created the attack

2024-09-12 15:25 UTC, Screaper91 commented
> I think that effects should be able to be applied and work on any hermit to keep the code easy to follow.

The reviewed changes are tested to check that other hermits using Beetlejhost's Jopacity with mocked attacks still reduce their damage and remove Chroma Keyed at a consistent time.

2024-09-12 15:53 UTC, Lunarmagpie commented
> Chroma Keyed is single purposed for Beetlejhost's Jopacity, it would not make sense for it to be re-used for another decaying special attack because then swapping between the two attacks would not reset the counter. I could move the damage reduction logic back, but it would require adding something like `AttackModel.isOrigin(source: Card): boolean` to check that `BeetlejhostRare` created the attack

I see what you mean. I think I had a hard time articulating my thoughts for this.
When someone looks at chroma keyed, everything should be there. I find that splitting up parts of the effect between the hermit and the effect leads to an issue where you don't know where the stuff is happening as a new developer, and once you do know it makes it harder to iterate on the code because the logic is split up. I also feel like this implementation is working around the Zombie Cleo and Rendog bugs instead of dealing with the root of the issue.

I feel like mock cards should be changed a bit to use the status effects of the target hermit. I think that might be the right move here.

2024-09-12 15:57 UTC, Lunarmagpie commented
I'm going to write my own version of the Cleo/Ren fixes. We probably can compare them. I feel like I need to program it to understand the full scope of this issue.

2024-09-12 20:32 UTC, Lunarmagpie commented
Just finished looking into this myself. I don't have much to show yet, but I feel something like `Attack.isOrigin` is the right way to go about this.

2024-09-12 22:18 UTC, Lunarmagpie commented
Actually I think this PR is the best way to do this, I have come full circle lol

2024-09-12 23:28 UTC, Lunarmagpie commented
Can you elaborate on why we need both `removeDamage` and `reduceDamage`?

2024-09-12 23:42 UTC, Screaper91 commented
- `removeDamage` is for attacks like Jopacity and World Eater that may deal less damage than `Hermit.secondary.damage`.
- `reduceDamage` is for Armor/Shield which reduce the total damage after damage multiplications.

Consecutive Jopacity vs Invisibility tails and Diamond Armor should be calculated as:
```
(
   Beetlejhost.secondary.damage /* Base Hermit damage */
   - 10 * ChromaKeyed.counter) /* Attack power reduction */
) * 2 /* Damage multiplier (e.g. Invisibility Tails) */
- 30 /* Total damage reduction (e.g. Diamond Armor) */
```
The hackier equivalent of `attack.removeDamage(component.entity, 10)` would be `attack.addDamage(component.entity, -10)`

2024-09-13 01:25 UTC, Lunarmagpie commented
I see. That makes sense.

2024-09-13 01:32 UTC, Lunarmagpie approved these changes

2024-09-13 05:59 UTC, Lunarmagpie commented on common/models/attack-model.ts
> +	public removeDamage(source: AttackerEntity, amount: number) {
I think this function should actually be called `subtractDamage` so it's clear it's the opposite of add. I think that would clear up the confusion I had a bit.

2024-09-13 14:32 UTC, Lunarmagpie commented on common/models/attack-model.ts
> +	public removeDamage(source: AttackerEntity, amount: number) {
Or maybe keeping this as `removeDamage` is fine, ill just go back and rename the other function since its kinda on the edge of what fits in this PR.

2024-09-13 14:32 UTC, merged