Add tests for a couple different older bugs
hc-tcg/hc-tcg pull request #889
Opened 2024-09-12 21:23 UTC by blockgoblin31

Tests added:
 - Add test for gaslight where afk hermit was attacked but took no damage https://github.com/hc-tcg/hc-tcg/pull/834
 - Add test for thorns with effect card https://github.com/hc-tcg/hc-tcg/pull/779
 - Add test for armor stand(Two bugfixes in 0.8.4)
 - Add test for anvil drop(Bugfixed in 0.8.3)

2024-09-12 22:32 UTC, Lunarmagpie commented
Thanks for the work! The armor stand tests will almost certainly be useful!

2024-09-12 22:39 UTC, Lunarmagpie requested changes
Right now the the thorns test only tests the Thorns I implementation and not Thorns II or Thorns III. I think theres two ways to go around it.
- Option 1: Extend the tests to test all of Thorns, Thorns II, and Thorns III.
- Option 2: Update Thorns so that they all have the same implementation. I was thinking there should be a function called `createThorns` or something that could return the thorns implementation based on some values so we don't need to duplicate code for all three thorns.

I would prefer option two, but if you want to go that route it would be best to remove the thorns test from the current PR and make a new one for just making thorns all depend on the same implementation.

2024-09-12 22:39 UTC, Lunarmagpie commented on tests/game/skizzleman-rare.test.ts
> +					//Use anvil to trigger attack on the afk hermit that does no damage
```suggestion
					// Use anvil to trigger attack the afk hermit for zero damage
```

2024-09-12 23:05 UTC, blockgoblin31 commented
> Right now the the thorns test only tests the Thorns I implementation and not Thorns II or Thorns III. I think theres two ways to go around it.
> 
> * Option 1: Extend the tests to test all of Thorns, Thorns II, and Thorns III.
> * Option 2: Update Thorns so that they all have the same implementation. I was thinking there should be a function called `createThorns` or something that could return the thorns implementation based on some values so we don't need to duplicate code for all three thorns.
> 
> I would prefer option two, but if you want to go that route it would be best to remove the thorns test from the current PR and make a new one for just making thorns all depend on the same implementation.

I just assumed they all used the same code, probably should have checked. I’ll look into doing a refactor.

2024-09-13 03:25 UTC, blockgoblin31 commented
I feel like refactoring the thorns is a bit of a bigger task because there's a bunch of other effects that really should be refactored too for consistency, so for now I'll add tests for each one separately

2024-09-13 14:02 UTC, Lunarmagpie approved these changes
LGTM

2024-09-13 14:14 UTC, merged

2024-09-13 15:25 UTC, blockgoblin31 commented
I’ve realized there’s a potential bug with the skizz test, I’ll fix it this afternoon